In [1]:
# import libraries
import numpy as np
from numpy import linalg as LA

# Initialize the matrices
A = np.matrix([[1, -2], [3, 4], [-5, 6]])
B = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
C = np.matrix([[2, 2, 1], [2, 3, 2], [1, 2, 2]])

AT = A.transpose()

In [2]:
def type_check(eigenvalues):
    greater = True
    equal = True  
    
    for x in eigenvalues:
        if x <= 0:
            greater = False
        if x < 0:
            equal = False

    if greater:
        print("The Matrix is Positive Definite")
    elif equal:
        print("The Matrix is Positive Semi-Definite")
    else:
        print("The Matrix is neither PD or PSD")  

In [3]:
# b ATA
print("3.b: A^T A")
ATA = np.matmul(AT, A)
print(ATA)

eig_vals_b, eig_vecs_b = LA.eig(ATA)
print("Eigenvalues: ", eig_vals_b)

type_check(eig_vals_b)

3.b: A^T A
[[ 35 -20]
 [-20  56]]
Eigenvalues:  [22.911286 68.088714]
The Matrix is Positive Definite


In [4]:
# c AAT
print("3.c: A A^T")
AAT = np.matmul(A, AT)
print(AAT)

eig_vals_c, eig_vecs_c = LA.eig(AAT)
print("Eigenvalues: ", eig_vals_c)

type_check(eig_vals_c)

3.c: A A^T
[[  5  -5 -17]
 [ -5  25   9]
 [-17   9  61]]
Eigenvalues:  [ 6.80887140e+01 -4.88498131e-15  2.29112860e+01]
The Matrix is neither PD or PSD


In [5]:
# d B
print("3.d: B")

eig_vals_d, eig_vecs_d = LA.eig(B)
print("Eigenvalues: ", eig_vals_d)

type_check(eig_vals_d)

3.d: B
Eigenvalues:  [1. 1. 1.]
The Matrix is Positive Definite


In [6]:
# e -B
print("3.e: -B")

E = -B

eig_vals_e, eig_vecs_e = LA.eig(E)
print("Eigenvalues: ", eig_vals_e)

type_check(eig_vals_e)

3.e: -B
Eigenvalues:  [-1. -1. -1.]
The Matrix is neither PD or PSD


In [7]:
# f C
print("3.f: C")

eig_vals_f, eig_vecs_f = LA.eig(C)
print("Eigenvalues: ", eig_vals_f)

type_check(eig_vals_f)

3.f: C
Eigenvalues:  [5.82842712 1.         0.17157288]
The Matrix is Positive Definite


In [8]:
# g C - 0.1 B
print("3.g: C - 0.1 B")
G = C - 0.1 * B

eig_vals_g, eig_vecs_g = LA.eig(G)
print("Eigenvalues: ", eig_vals_g)

type_check(eig_vals_g)

3.g: C - 0.1 B
Eigenvalues:  [5.72842712 0.9        0.07157288]
The Matrix is Positive Definite


In [9]:
# h C - 0.01 AAT
print("3.h: C - 0.01 AAT")
H = C - 0.01 * AAT

eig_vals_h, eig_vecs_h = LA.eig(H)
print("Eigenvalues: ", eig_vals_h)

type_check(eig_vals_h)

3.h: C - 0.01 AAT
Eigenvalues:  [ 5.60967481  0.51610854 -0.03578335]
The Matrix is neither PD or PSD
